zgrmbl

diff --git a/scripts/install b/scripts/install
--- a/scripts/install
+++ b/scripts/install
@@ -85,7 +85,7 @@ ynh_setup_source --dest_dir="$tmpdir" --source_id="deb-multimedia-keyring"
 dpkg -i "$tmpdir/deb-multimedia-keyring.deb"
 
 if [ ${PACKAGE_CHECK_EXEC:-0} -eq 1 ]; then
-        ynh_install_extra_app_dependencies --repo="deb http://deb.debian.org/debian $(ynh_get_debian_release) contrib non-free" --package="nvidia-vdpau-driver nvidia-installer-cleanup nvidia-legacy-check libvdpau1 nvidia-alternative"
+    #ynh_install_extra_app_dependencies --repo="deb http://deb.debian.org/debian $(ynh_get_debian_release) contrib non-free" --package="nvidia-vdpau-driver nvidia-installer-cleanup nvidia-legacy-check libvdpau1 nvidia-alternative"
 	pkg_dependencies="$pkg_dependencies $package_check_dependencies"
 fi
 
@@ -98,6 +98,10 @@ fi
 if [ ${PACKAGE_CHECK_EXEC:-0} -eq 1 ]; then
 	cp ../conf/xorg.conf /etc/X11/xorg.conf
 fi
+
+#FIXME : this is only for debugging on the CI ...
+LIBVA_DRIVER_NAME=nvidia /usr/bin/xinit /usr/bin/dbus-launch --exit-with-session /usr/lib/x86_64-linux-gnu/kodi/kodi-xrandr
+exit 1
 
 #=================================================
 # CREATE DEDICATED USER
